# Application
spring:
  application:
    name: Oppenheimer

  datasource:
    url: jdbc:h2:mem:oppenheimer-db
    username: oppenheimer
    password: oppenheimer
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 15000

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true
      use_sql_comments: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog.sql
    liquibase-schema: public

  devtools:
    add-properties: false

# Server
server:
  port: 8080
  shutdown: graceful
  graceful:
    timeout: 30s
  servlet:
    context-path: /oppenheimer

reactor:
  netty:
    ioWorkerCount: 4
    pool:
      leasingStrategy: fifo

logging:
  level:
    root: OFF
    reactor.netty: INFO
    org.springframework.web: INFO
    com.nisum.oppenheimer: INFO

springdoc:
  show-actuator: false
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

token:
  expiration: 86400000
  key: dLGC4NvgKCYv/kNt1wK8KkIRfWSnUTBBc7wB1JYybcs=

password:
  regex: ^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@#$%^&+=]).*$
  saltLength: 16
  hashLength: 32
  parallelism: 1
  memory: 60000
  iterations: 10

