apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: oppenheimer
  name: oppenheimer-volume
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    volume: oppenheimer
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: oppenheimer
  name: oppenheimer-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: oppenheimer-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Mi
